version: "3"

services:
  gateway:
    image: deadcoder11u2/asyph
    container_name: asyph-gateway
    ports:
      - 8080:8080
    networks:
      consul_network:
        ipv4_address: 99.0.0.5
  userService:
    image: deadcoder11u2/asyph-user
    container_name: asyph-user
    ports:
      - 8085:8085
    environment:
      "GMAIL_PASSWORD": ${GMAIL_PASSWORD}
      "ASTRA_API_APPLICATION-TOKEN": "${ASTRA_API_APPLICATION_TOKEN}"
      "ASTRA_API_DATABASE-ID": "${ASTRA_API_DATABASE_ID}"
      "ASTRA_API_DATABASE-REGION": "${ASTRA_API_DATABASE_REGION}"
      "ASTRA_CQL_DRIVER-CONFIG_BASIC_SESSION-KEYSPACE": "${ASTRA_CQL_DRIVER_CONFIG_BASIC_SESSION_KEYSPACE}"
      "GMAIL_ACCOUNT": "${GMAIL_ACCOUNT}"
    networks:
      consul_network:
        ipv4_address: 99.0.0.6
  problemService:
    image: deadcoder11u2/asyph-problems
    container_name: asyph-problem
    ports:
      - 8086:8086
    environment:
      "GMAIL_PASSWORD": ${GMAIL_PASSWORD}
      "ASTRA_API_APPLICATION-TOKEN": "${ASTRA_API_APPLICATION_TOKEN}"
      "ASTRA_API_DATABASE-ID": "${ASTRA_API_DATABASE_ID}"
      "ASTRA_API_DATABASE-REGION": "${ASTRA_API_DATABASE_REGION}"
      "ASTRA_CQL_DRIVER-CONFIG_BASIC_SESSION-KEYSPACE": "${ASTRA_CQL_DRIVER_CONFIG_BASIC_SESSION_KEYSPACE}"
      "GMAIL_ACCOUNT": "${GMAIL_ACCOUNT}"
    networks:
      consul_network:
        ipv4_address: 99.0.0.7
networks:
networks:
  consul_network:
    driver: bridge
    ipam:
      config:
        - subnet: 99.0.0.0/16
