version: "2.1"

jobs:
  build:
    docker:
      - image: circleci/openjdk
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      - run: cd ApiGateway && chmod +x gradlew && ./gradlew
      - run: gradle build

workflows:
  build:
    jobs:
      - build
