version: "2.1"

jobs:
  build:
    docker:
      - image: cimg/openjdk:18.0.2
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      - run: cd ApiGateway && chmod +x ./gradlew && ./gradlew
      - run: gradle ApiGateway:bootJar --scan -s
      - run: gradle OnlineJudge:bootJar --scan -s
      - run: gradle ProblemsAndContestService:bootJar --scan -s
      - run: gradle UserMicroservice:bootJar --scan -s


workflows:
  build:
    jobs:
      - build
