version: "2.1"

jobs:
  build:
    docker:
      - image: cimg/openjdk:18.0.2
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      - run: cd ApiGateway && chmod +x ./gradlew && ./gradlew bootJar --scan -s

workflows:
  build:
    jobs:
      - build
