version: "2.1"

jobs:
  build:
    docker:
      - image: circleci/openjdk
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - run: echo "Build..."

workflows:
  build:
    jobs:
      - build
