version: "2.1"

jobs:
  build:
    docker:
      - image: circleci/openjdk
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-
      - run: chmod +x ApiGateway/gradlew && bash ApiGateway/gradlew
      - run: gradle dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
      - run: cd ApiGateway && gradle build
      - run: cd UserMicroservice && gradle build
      - run: cd ProblemsAndContestService && gradle build
      - run: cd OnlineJudge && gradle build


workflows:
  build:
    jobs:
      - build
