astra:
  api:
    application-token: AstraCS:eBvppEAKKiepKjaHacUYOIXh:2417027c04add8004b802a60a0375cef2b6889fd83f37fd2c00602bad9f09346
    database-id: fa917e0b-bbef-4d30-8557-bfa830d92d4f
    database-region: asia-south-1
    cross-region-failback: false
    grpc:
      enabled: true
  cql:
    enabled: true
    download-scb:
      enabled: true
    driver-config:
      basic:
        session-keyspace:
          onlinejudge
spring:
  application:
    name: Auth-Service
  data:
    cassandra:
      schema-action: CREATE_IF_NOT_EXISTS

ASYPH_ACCOUNT: ksrikanth200212@gmail.com

server:
  port: 8083


zuul:
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 60000
  routes:
    problems-and-contest:
      path: /problems-and-contest/**
      service-id: PROBLEM-CONTEST-SERVICE
      url: http://localhost:8084
    user-service:
      path: /user-data/**
      service-id: USER-SERVICE
      url: http://localhost:8082

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: https://eureka-server-deadcoder11u2.herokuapp.com/eureka/

management:
  endpoints:
    web:
      exposure:
        include: '*'
      cors:
        allowed-methods: GET
        allowed-origins: '*'
  endpoint:
    routes:
      enabled: true
    health:
      show-details: always
logging:
  level:
    org:
      springframework:
        cloud:
          netflix: trace
